export const textLight = '#fff'
export const textDark = '#000'
export const primary = '#c83737'
export const secondary = '#c0ad47'
// export const secondary = '#005cb2'
// export const secondary = '#1d2535'
