export const textLight = '#fff'
export const textDark = '#000'
export const secondary = '#c0ad47'
// export const secondary = '#005cb2'
// export const secondary = '#1d2535'
export const primaryText = '#cbd5ff'
export const primary = '#3A7D44'
export const primaryDark = '#7481b4'
export const PrimaryLight = 'green'

export const red = '#ff0000'
export const darkRed = '#39bd22'
export const orange = '#e76f51'
export const orangeDark = '#c83737'
